services:
  - type: web
    name: mckl-chatbot-backend
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn server:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY
      - key: OPENAI_MODEL
        fromSecret: OPENAI_MODEL
      - key: CHUNK_SIZE
        fromSecret: CHUNK_SIZE
      - key: CHUNK_OVERLAP
        fromSecret: CHUNK_OVERLAP
